name: End-to-End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress and JSON Server
        run: npm install cypress json-server --save-dev

      # 启动 JSON Server 后端
      - name: Start JSON Server
        run: |
          npx json-server --watch db.json --port 3001 &
          echo "JSON Server started on port 3001"
          sleep 5  # 等待服务启动

      # 启动 React 应用
      - name: Start React app
        run: |
          npm start -- --port=3000 &
          echo "Waiting for React app to start..."
          sleep 10
          echo "React app started on port 3000"

      # 运行 Cypress 测试
      - name: Run Cypress tests
        run: npx cypress run --browser chrome
        env:
          CYPRESS_BASE_URL: http://localhost:3000
          CYPRESS_API_URL: http://localhost:3001
